### ISSUE TITLE
Problem with spaCy 3

### ISSUE THREAD

**Issue by reckart** [inception-project/inception-external-recommender#20] opened 2021-02-10 21:00 UTC
The code is presently not compatible with spaCy 3 - but if one follows the instructions in the README.md, spaCy 3 is what the user gets.

Either the code needs to be updated for compatibility with spaCy 3 or the repo needs to pin the version of spaCy down to the latest 2.x version.

**Comment by jcklie** [comment] 2021-02-11 09:07
Duplicate of #19

**Closed by jcklie** 2021-02-11 09:07 UTC
Labels: bug
